# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/aditya/projects/hypervisor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/aditya/projects/hypervisor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/aditya/projects/hypervisor/CMakeFiles /mnt/c/aditya/projects/hypervisor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/aditya/projects/hypervisor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_program

# Build rule for target.
my_program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_program
.PHONY : my_program

# fast build rule for target.
my_program/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/build
.PHONY : my_program/fast

db/db.o: db/db.cpp.o
.PHONY : db/db.o

# target to build an object file
db/db.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/db/db.cpp.o
.PHONY : db/db.cpp.o

db/db.i: db/db.cpp.i
.PHONY : db/db.i

# target to preprocess a source file
db/db.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/db/db.cpp.i
.PHONY : db/db.cpp.i

db/db.s: db/db.cpp.s
.PHONY : db/db.s

# target to generate assembly for a file
db/db.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/db/db.cpp.s
.PHONY : db/db.cpp.s

hypervisor_main/hypervisor.o: hypervisor_main/hypervisor.cpp.o
.PHONY : hypervisor_main/hypervisor.o

# target to build an object file
hypervisor_main/hypervisor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/hypervisor_main/hypervisor.cpp.o
.PHONY : hypervisor_main/hypervisor.cpp.o

hypervisor_main/hypervisor.i: hypervisor_main/hypervisor.cpp.i
.PHONY : hypervisor_main/hypervisor.i

# target to preprocess a source file
hypervisor_main/hypervisor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/hypervisor_main/hypervisor.cpp.i
.PHONY : hypervisor_main/hypervisor.cpp.i

hypervisor_main/hypervisor.s: hypervisor_main/hypervisor.cpp.s
.PHONY : hypervisor_main/hypervisor.s

# target to generate assembly for a file
hypervisor_main/hypervisor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/hypervisor_main/hypervisor.cpp.s
.PHONY : hypervisor_main/hypervisor.cpp.s

instance_main/instance.o: instance_main/instance.cpp.o
.PHONY : instance_main/instance.o

# target to build an object file
instance_main/instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/instance_main/instance.cpp.o
.PHONY : instance_main/instance.cpp.o

instance_main/instance.i: instance_main/instance.cpp.i
.PHONY : instance_main/instance.i

# target to preprocess a source file
instance_main/instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/instance_main/instance.cpp.i
.PHONY : instance_main/instance.cpp.i

instance_main/instance.s: instance_main/instance.cpp.s
.PHONY : instance_main/instance.s

# target to generate assembly for a file
instance_main/instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/instance_main/instance.cpp.s
.PHONY : instance_main/instance.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/main.cpp.s
.PHONY : main.cpp.s

mini_ssh/mini_ssh.o: mini_ssh/mini_ssh.cpp.o
.PHONY : mini_ssh/mini_ssh.o

# target to build an object file
mini_ssh/mini_ssh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/mini_ssh.cpp.o
.PHONY : mini_ssh/mini_ssh.cpp.o

mini_ssh/mini_ssh.i: mini_ssh/mini_ssh.cpp.i
.PHONY : mini_ssh/mini_ssh.i

# target to preprocess a source file
mini_ssh/mini_ssh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/mini_ssh.cpp.i
.PHONY : mini_ssh/mini_ssh.cpp.i

mini_ssh/mini_ssh.s: mini_ssh/mini_ssh.cpp.s
.PHONY : mini_ssh/mini_ssh.s

# target to generate assembly for a file
mini_ssh/mini_ssh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/mini_ssh.cpp.s
.PHONY : mini_ssh/mini_ssh.cpp.s

mini_ssh/server.o: mini_ssh/server.cpp.o
.PHONY : mini_ssh/server.o

# target to build an object file
mini_ssh/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/server.cpp.o
.PHONY : mini_ssh/server.cpp.o

mini_ssh/server.i: mini_ssh/server.cpp.i
.PHONY : mini_ssh/server.i

# target to preprocess a source file
mini_ssh/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/server.cpp.i
.PHONY : mini_ssh/server.cpp.i

mini_ssh/server.s: mini_ssh/server.cpp.s
.PHONY : mini_ssh/server.s

# target to generate assembly for a file
mini_ssh/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/server.cpp.s
.PHONY : mini_ssh/server.cpp.s

mini_ssh/shell.o: mini_ssh/shell.c.o
.PHONY : mini_ssh/shell.o

# target to build an object file
mini_ssh/shell.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/shell.c.o
.PHONY : mini_ssh/shell.c.o

mini_ssh/shell.i: mini_ssh/shell.c.i
.PHONY : mini_ssh/shell.i

# target to preprocess a source file
mini_ssh/shell.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/shell.c.i
.PHONY : mini_ssh/shell.c.i

mini_ssh/shell.s: mini_ssh/shell.c.s
.PHONY : mini_ssh/shell.s

# target to generate assembly for a file
mini_ssh/shell.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_program.dir/build.make CMakeFiles/my_program.dir/mini_ssh/shell.c.s
.PHONY : mini_ssh/shell.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my_program"
	@echo "... db/db.o"
	@echo "... db/db.i"
	@echo "... db/db.s"
	@echo "... hypervisor_main/hypervisor.o"
	@echo "... hypervisor_main/hypervisor.i"
	@echo "... hypervisor_main/hypervisor.s"
	@echo "... instance_main/instance.o"
	@echo "... instance_main/instance.i"
	@echo "... instance_main/instance.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mini_ssh/mini_ssh.o"
	@echo "... mini_ssh/mini_ssh.i"
	@echo "... mini_ssh/mini_ssh.s"
	@echo "... mini_ssh/server.o"
	@echo "... mini_ssh/server.i"
	@echo "... mini_ssh/server.s"
	@echo "... mini_ssh/shell.o"
	@echo "... mini_ssh/shell.i"
	@echo "... mini_ssh/shell.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

